config/routes.rb
Railschan::Application.routes.draw do
  root to: 'boards#index'

  resources :boards do
    resources :posts
  end

end

app/models/board.rb
class Board
  include Mongoid::Document

  field :name
  field :short_name

  key :short_name # Access the board via /b/, e.g.

  embeds_many :posts

end

app/models/post.rb
class Post
  include Mongoid::Document
  recursively_embeds_many

  field :author
  field :author_email
  field :subject
  field :content
  field :post_number, type: Integer

  key :post_number

  mount_uploader :image, ImageUploader

  embedded_in :board

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boards }
    end
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @board = Board.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @board }
    end
  end

  # GET /boards/new
  # GET /boards/new.json
  def new
    @board = Board.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @board }
    end
  end

  # GET /boards/1/edit
  def edit
    @board = Board.find(params[:id])
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(params[:board])

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render json: @board, status: :created, location: @board }
      else
        format.html { render action: "new" }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boards/1
  # PUT /boards/1.json
  def update
    @board = Board.find(params[:id])

    respond_to do |format|
      if @board.update_attributes(params[:board])
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board = Board.find(params[:id])
    @board.destroy

    respond_to do |format|
      format.html { redirect_to boards_url }
      format.json { head :ok }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @board = Board.find(params[:board_id])
    if(params[:parent_post]) #If I came from the reply post page
      @parent = @board.posts.find(params[:parent_post])
      @post = @parent.child_posts.build(params[:post]).save
    else
      @post = @board.posts.create!(params[:post])
    end
    redirect_to @board, notice: 'Post successful'
  end

  def new
    @board = Board.find(params[:board_id])
    @post = Post.new
  end

  def show
    @board = Board.find(params[:board_id])
    @post = @board.posts.find(params[:id])
    @replies = @post.child_posts
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/posts_thread_helper.rb
module PostsThreadHelper
end

app/views/boards/_form.html.haml
= form_for @board do |f|
  -if @board.errors.any?
    #error_explanation
      %h2= "#{pluralize(@board.errors.count, "error")} prohibited this board from being saved:"
      %ul
        - @board.errors.full_messages.each do |msg|
          %li= msg
  %p
    %label{for: 'name'} Name
    = f.text_field :name
  %p
    %label{for: 'short_name'} Short Name
    = f.text_field :short_name

  .actions
    = f.submit 'Save'

app/views/boards/edit.html.haml
%h1 Editing board

= render 'form'

= link_to 'Show', @board
\|
= link_to 'Back', boards_path

app/views/boards/index.html.haml
%h1 Listing boards

%table
  %tr
    %th
    %th
    %th

  - @boards.each do |board|
    %tr
      %td= board.short_name
      %td= board.name
      %td= link_to 'Show', board
      %td= link_to 'Edit', edit_board_path(board)
      %td= link_to 'Destroy', board, :confirm => 'Are you sure?', :method => :delete

%br

#boards
:javascript
  $(function() {
    window.router = new Railschan.Routers.BoardsRouter({boards: <%= @boards.to_json.html_safe -%>});
    Backbone.history.start();
  });

= link_to 'New Board', new_board_path

app/views/boards/new.html.haml
%h1 New board

= render 'form'

= link_to 'Back', boards_path

app/views/boards/show.html.haml
%p#notice= notice

#post_form
  =form_for [@board, Post.new] do |f|
    %p
      %label{for: 'author'} Name
      = f.text_field :author
    %p
      %label{for: 'author_email'} E-mail
      = f.text_field :author_email
    %p
      %label{for: 'subject'} Subject
      = f.text_field :subject
    %p
      %label{for: 'image'} Image
      = f.file_field :image
    %p
      %label{for: 'content'} Comment
      = f.text_area :content
    %p
      = f.submit

.posts
  -if @board.posts.size > 0
    -for post in @board.posts
      -unless post.parent_post
        #post
          %table
            %tr
              %td
                #post_image
                  = link_to(image_tag(post.image.thumb.url), post.image.url)
              %td
                %ul#post_info
                  %li
                    =link_to '[Reply]', [@board, post]
                  %li
                    %strong Name:
                    = post.author
                  %li
                    %strong E-Mail:
                    = post.author_email
                  %li
                    %strong Subject:
                    = post.subject
                %p
                  = post.content

= link_to 'Edit', edit_board_path(@board)
\|
= link_to 'Back', boards_path

app/views/layouts/application.html.haml
%html
  %head
    %title RailsChan
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tag
  %body
    = render 'shared/header'
    = yield

app/views/posts/_form.html.haml
= form_for @post do |f|
  %p
    %label{for: 'author'} Name
    = f.text_field :author
  %p
    %label{for: 'author_email'} E-mail
    = f.text_field :author_email
  %p
    %label{for: 'subject'} Subject
    = f.text_field :subject
  %p
    %label{for: 'image'} Image
    = f.file_field :image
  %p
    %label{for: 'content'} Comment
    = f.text_area :content
  %p
    = f.submit

app/views/posts/create.html.haml
%h1 Posts#create
%p
  Name:
  = @post.author
%p
  E-Mail:
  = @post.author_email
%p
  Subject:
  = @post.subject
%p
  Image:
  = image_tag @post.image.url
%p
  Comment:
  = @post.content

app/views/posts/new.html.haml
%h1 Posts#new
= render 'form'

app/views/posts/show.html.haml
#post_form
  =form_for [@board, @replies.build] do |f|
    %p
      %label{for: 'author'} Name
      = f.text_field :author
    %p
      %label{for: 'author_email'} E-mail
      = f.text_field :author_email
    %p
      %label{for: 'subject'} Subject
      = f.text_field :subject
    #post_image
      %label{for: 'image'} Image
      = f.file_field :image
    %p
      %label{for: 'content'} Comment
      = f.text_area :content
    %p
      = hidden_field_tag 'parent_post', @replies.first.parent_post.id.to_s
      = f.submit


#main_post
  %table
    %tr
      %td
        #post_image
          = link_to(image_tag(@post.image.thumb.url), @post.image.url)
      %td
        %ul#post_info
          %li
            %strong Name:
            = @post.author
          %li
            %strong E-Mail:
            = @post.author_email
          %li
            %strong Subject:
            = @post.subject
        %p
          = @post.content

  .posts
    -unless @replies.empty?
      -@replies.each do |reply|
        #post
          %table
            %tr
              %td
                #reply_image
                  = link_to(image_tag(reply.image.thumb.url), reply.image.url)
              %td
                %ul#post_info
                  %li
                    %strong Name:
                    = reply.author
                  %li
                    %strong E-Mail:
                    = reply.author_email
                  %li
                    %strong Subject:
                    = reply.subject
                %p
                  = reply.content

app/views/shared/_header.html.haml
= Board.all.each do |b|
  %ul#board_list
    %li
      = link_to("[#{b.short_name}]", b)